### ISSUE TITLE
"Object doesn't support this action" error in IE11

### ISSUE THREAD

**Issue by mikeebee** [gmrchk/swupjs#10]
Hi there! Got this absolutely marvellous library working amazingly well on a site, used the original version to start but moved to the JS version to get a bit more control over the animations.

In IE11 (Version 11.0.20 on Windows 10 via VirtualBox) I'm getting this error when creating a new instance of `Swupjs` - `new Swupjs()`, at first, given where the error is I thought it might be something to do with the custom events I am using, but deleting those didn't affect anything, it's just happens on init. The error is:

`Object doesn't support this action` which, according to IE dev tools is coming from this line:

```
// trigger event on document with prefix "swup:"
var event = new CustomEvent('swup:' + eventName, { detail: eventName });
```

My options are just using the defaults.

Not sure if it's relevant but all my scripts are compiled using Babel and I have the babel polyfill also.

Hopefully that's enough to go on! If there is any more information I can give you please let me know.

Many thanks,
Mike

**Comment by gmrchk** [comment]
Hi, thank you for reporting.

I am assuming the error happens on both swup and swupjs, but it just happens to be the swupjs you opened in the IE11 browser?   

Unfortunately, swup doesn't fully support IE11 (I will add that to the documentation), but that can be solved with a few polyfills. It looks like you are already using a promise polyfill, as that is also not supported by IE11 and required by swup, so adding the polyfill for CustomEvent as well will solve this issue. Some more polyfills might be required (if so, please, let me know which).

From my experience, you can make the animated page transitions work in IE11 (and even older), but the outcome just isn't what one would like it to be, due to some performance issues of those browsers, so I would usually just disable swup in IE browsers and don't worry about polyfills. As swup serves as an enhancement of static website, there should be no issue with that.

**Comment by mikeebee** [comment]
Hello!

Yes this issue was found in both libraries.

Ah that makes perfect sense, I'll opt for the sensible approach of disabling it for any browsers that might struggle. I'm pretty sure IE11 would set on fire with the animations I'm doing anyway!

Thanks for clarifying and again, thanks so much for this plugin, it's an absolute belter!
